drop table if exists book;
drop table if exists author;
create table author
(
    id   bigint generated by default as identity
        constraint author_pkey
            primary key,
    name varchar(255)
);
insert into author(name)
VALUES ( 'Stephen King' ),
       ('Fredrik Backman');

