create table book
(
    id        bigint generated by default as identity
        constraint book_pkey
            primary key,
    name      varchar(255),
    author_id bigint
        constraint fkklnrv3weler2ftkweewlky958
            references author
);
insert into book(name, author_id)
VALUES ('it', 1),
       ('Shining', 1),
       ('The Stand', 1),
       ('The man called Ove', 2),
       ('Beartown', 2),
       ('New  Beartown', 2);

