create table book
(
    id        bigint generated by default as identity
        constraint book_pkey
            primary key,
    name      varchar(255),
    author_id bigint
        constraint fkklnrv3weler2ftkweewlky958
            references author
);

