drop table if exists book;
drop table if exists author;
drop sequence if exists seq_auth;
drop sequence if exists seq_book;
create sequence seq_auth start with 1001;
create sequence seq_book start with 1001;

create table author
(
    id   bigint generated by default as identity
        constraint author_pkey
            primary key,
    name varchar(255)
);
create table book
(
    id        bigint generated by default as identity
        constraint book_pkey
            primary key,
    name      varchar(255),
    author_id bigint
        constraint fkklnrv3weler2ftkweewlky958
            references author
);

alter table book add column isBestSeller boolean default true;
